### ISSUE TITLE
Add extract LFC in calibDB sequence

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#661]
please add the extraction of the files containing the LFC spectra in each calibration sequence. 
They contain the SBCCAS_P or SBCREF_P == pos_rs
Thanks

**Comment by njcuk9999** [comment]
You'll have to be more specific...

We can preprocess and extract LFC spectra

Did
`cal_preprocess_spirou.py NIGHT FILENAME`   fail?

Did
`cal_extract_spirou.py NIGHT FILENAME` fail?

They shouldn't for LFC - we have preprocessed and extracted successfully



What you may mean is that apero_processing.py is not automatically processing them.
This is also incorrect - it depends on your `run.ini` file


It is correct that we do not extract LFC files with the `limited_seq` or `full_seq` i.e. the `RUN_EXTOBJ` or `RUN_EXTTELLU` commands - because these specifically extract science objects and telluric objects

but there is an "engineering sequence" (`eng_seq`) that has options to extract other things: i.e. 
- `RUN_EXT_HC1HC1`   for extracting HC_HC files  
- `RUN_EXT_FPFP` for extracting FP_FP files
- `RUN_EXT_DFP` for extracting DARK_FP files
- `RUN_EXT_LFC` for extracting LFC_LFC files

So you need to use this `eng_seq` with these options (and the equivalent pp runs) to have apero_processing.py reduce these files

**Comment by clairem789** [comment]
more details: 
-yes, these commands are not run by the apero-processing sequences. I tried to find the sequences to update them but did not :(
-yes, pp and extract do work with LFC, I checked manually on one file

I copy Andres so that he can help me find the eng_seq and add the LFC extraction systematically when we process a set of data with new calibrations. (pp is already available for these files)
thanks!

**Comment by njcuk9999** [comment]
Just to finish this off (as the discussion moved to email):

- I have added `LFC_FP` and `FP_LFC` file definitions 
- I have added `PP_LFCFP`,  `PP_FPLFC`, `EXT_LFCFP` and `EXT_FPLFC` to the "engineering sequence" `eng_seq`  as well as the LFCLFC ones being there already

So now when using `eng_seq` in a run.ini file you can use:
```
RUN_PP_LFC = False
RUN_PP_LFCFP = False
RUN_PP_FPLFC = False
```
and
```
SKIP_EXT_LFC = False
SKIP_EXT_LFCFP = False
SKIP_EXT_FPLFC = False
```

To preprocess and extract these files.

I've updated developer branch and 0.7 with these options
