### ISSUE TITLE
QC failure shape in 21AQ03 Q05 and Q10 (start Feb 19)

### ISSUE THREAD

**Issue by larnoldgithub** [njcuk9999/apero-drs#668]
QC   QCC003V (YRES) jumps above above the 0.1 limit and is above 0.2
QC QCC002V (XRES) also jumps but remains below the limit.

The run 21AQ08 is okay.

See attached plot for 20B and 21A:
![Screen Shot 2021-05-11 at 17 28 06](https://user-images.githubusercontent.com/59746974/117914539-47cadd00-b27f-11eb-9683-b0bf2a7d694f.png)

**Comment by njcuk9999** [comment]
Thanks for this Luc - something definitely changed.

Do you know if anything special happened on these nights that could explain this?

I'd like @eartigau to take a look at this or at least tell us what exactly this YRES value means.

@CharlesCadieux could you confirm we see the same in our data? (this would rule something going wrong at your end)

**Comment by CharlesCadieux** [comment]
I'll take a look at this and get back to you shortly.

**Comment by larnoldgithub** [comment]
Let me know if you need to have a look at some specific fits or log files, I could easily make them available to you through my dropbox or something equivalent.

**Comment by larnoldgithub** [comment]
About what could trigger this:   21AQ03 is the first run where the date have been reduced with our new quicklook set up. But this setup is using a clone of our 'offline' calibDB, and process each night as the offline does: We wait until the end of the morning cals to start the cals processing and the follow with the o.fits extraction etc.  The curious thing is that QC look ok for the 21AQ08 run, but nothing changed on the drs side.

**Comment by njcuk9999** [comment]
Assuming you are running calibrations (which you must be as you are having qc values to plot so you have shapel files) the quick look doesn't do anything to the shape recipe - it will only affect extraction onwards - so calibrations are not affected by quick look.

I imagine it will have to be something with the observation that has changed.

**Comment by larnoldgithub** [comment]
Not sure I understand what you mean Neil. The quicklook does reduce the calibrations, so it's using the shape recipe, write in the calibDB, and after that proceed with the extraction of all observations of the night, exactly as the offline is working.

I don't understand what you mean by  'calibrations are not affected by quick look'

**Comment by njcuk9999** [comment]
I'll rephrase. You have shapel.fits files - that means you are running calibrations - assuming you have all other calibrations and are not changing any of the DRS code -  it can't see how it has anything to do with your quick look.

It probably indicates a change in the detector / telescope or something that happened during taking those sequences.

**Comment by CharlesCadieux** [comment]
Hi Neil and Luc,
I confirm we see the same QC values (XRES and YRES) as Luc shown in our MTL log.fits for the cal_shape_spirou.py recipe, as can be seen here:
https://www.astro.umontreal.ca/~charles/shape_test1/check5/check5.html

**Comment by larnoldgithub** [comment]
yes I agree thanks

**Comment by larnoldgithub** [comment]
before the first night of 21A we installed a spaced between the telescope and the SPIRou Cass unit and we had to adjust the focus quite significantly.  So this maybe has change slightly the shape of the spectrum on the detector. The weird thing is that the 21AQ08 looks okay. I'm checking details with Greg here.

**Comment by njcuk9999** [comment]
From @eartigau:

To determine the  accurate shift between a nightly FP and the master FP, we first find the round pixel offset. To do so, we put the master FP peaks on a binary mask of the night's FP peaks and count the number of matches for a range of offsets. Normally, the best match is the shift with the largest fraction of FP peaks falling at peak positions on the mask. As the slicer has 4 peaks, you get 'outriggers' in that correlation map where ~75% of peaks are matched, meaning that you are off by 1 slice width (slice 1-2-3 in on image are matched to slices 2-3-4 in the other). Normally this works nicely, but we had a problem when the detector moved by nearly 0.5 pixel. We ended with 50%/50% of good matches for two different pixels corresponding to the correct offset and 75% corresponding to the offset by 1 slice.

To fix if, we now 'smooth' the correlation map, so that two pixels at 0.5 count more than a single pixel at 0.75

Here is the correlation before where the peak correlation is at (x=9, y=14) and is only very slightly higher than the intended position - at (x=9 or 10, y=11) (for one of the files that failed qc):
![luc_shape_qc_before](https://user-images.githubusercontent.com/6008608/118536220-72061a00-b719-11eb-91db-2394cffddb74.png)

Here is the correlation after Etienne's fix where the peak correlation is now in the center (for the same file):
![luc_shape_qc_after](https://user-images.githubusercontent.com/6008608/118536238-77fbfb00-b719-11eb-9496-e88b844fbff1.png)


So just to point out this will now be fixed in the `developer` (0.6.132 version) and in 0.7.XXX version.

**Comment by njcuk9999** [comment]
From how Etienne explained it to me it sounds like the detector was slowly drifting to this point where you were 50/50 over this correlation point and eventually it would have drifted past - it might also explain why we see one night fail, then the next night okay (a slight drift back) then the next after that fail - its almost an "off / on " switch as well so wouldn't have been caught by a slow rise in the QC.

**Comment by larnoldgithub** [comment]
Thanks @eartigau and @njcuk9999 ! I undrstand that we can download the update for the 0.6.132 and maybe I will reprocess the 3 runs for which we had this numerical 'instability'

**Comment by larnoldgithub** [comment]
(I'm wondering if the recurrent failing shape issues we had last year with the DRS 0.5 could be related to the same issue you are discribing Etienne...  not important but just curious)

**Comment by CharlesCadieux** [comment]
List of nights (starting on 2021-02-20; row 90): https://www.astro.umontreal.ca/~charles/shape_test1/check4/check4.html
