### ISSUE TITLE
input data for BERV calculation

### ISSUE THREAD

**Issue by clairem789** [njcuk9999/apero-drs#674]
hi, 
We have a question about the input data given for the BERV calculation. Where can we find the exact definition of input parameters? Alternatively, Merwan can give examples of the discrepant values he's observing for some stars. thanks!

**Comment by njcuk9999** [comment]
We know 0.6 is broken for the BERV in several ways so don't waste too much time on it please.
1. the object name to Gaia identification is broken for some objects - I'm pretty sure most of your problems come from this
2. barycorrpy has some problems in 0.6 - it is an older version - so you may get to pyasl berv estimates some times

So for 0.6 its here:
https://github.com/njcuk9999/apero-drs/blob/developer/apero/science/extract/berv.py#L152

For 0.7 it was completely reworked because it just wasn't very clear and we have all the problems with object name
https://github.com/njcuk9999/apero-drs/blob/v0.7.166-working/apero/science/extract/berv.py#L150

Assuming you are only looking at 0.6 the logic goes as follows:

1. we check that we should do the BERV (only should do it for science objects)
2. we check the header for information (input keys and output keys - to make sure the berv isn't there already as well as get values in the header for doing the berv)
3. if berv was found (`bprops is not None`) we have a BERV so we don't continue
4. we get the parameters (this is from the header and from the database file and deals with not having an entry in the database) in theory all entries should make it into the database - so those will be the values used but I know there have been problems with this - hence part of the re-write
5. we use barycorrpy with the parameters (if `kind=='barycorrpy'`) - we return the BERV here if successful
6.  if we get to this point we default back to a BERV estimate (pyasl) this is a fall back that populates BERVEST instead of BERV with warnings about using an estimate for PRV (for tellurics its probably fine it is good to 10 m/s or so)


0.7 follows a similar logic but has been re-ordered - the getting of berv parameters and matching to Gaia and by object name is now done in preprocessing - and seems to work a lot better than 0.6!

**Comment by HkmMerwan** [comment]
Hi, so I have been trying to correct the BERV by myself using barycorrpy and I have different results with the DRS


```
from barycorrpy import get_BC_vel , exposure_meter_BC_vel
from barycorrpy.utils import get_stellar_data
get_stellar_data(target)

stellar_data = get_stellar_data(target)[0]
```

And for all stars the RA, DEC, PM_RA, PM_DEC and PLX are different. For GL411 the header even gives parallax of 0.

However when computing the BERV it is not consistant with this observation. I have been comparing the BERV in the lbl files with the one I compute for both input (the header and the one I get with the code above).

In the case of GL411, using the same header as the DRS gives this BERV difference

![image](https://user-images.githubusercontent.com/76592606/135462575-6dc919ae-ee00-4aac-b695-8a2121f098fa.png)

And this one when using my coordinates 

![image](https://user-images.githubusercontent.com/76592606/135462667-20aeeb5a-30c7-4ba3-aefe-e1632286db1c.png)

It is what you would expect (different input, different ouput) **_BUT_** when doing the same thing with GL436 for instance you would have with **the same input** : 

![image](https://user-images.githubusercontent.com/76592606/135462991-8c530f90-6777-4631-a9c2-05ff9cdfb23b.png)

And with my coordinates

![image](https://user-images.githubusercontent.com/76592606/135463135-bac91e9b-01a5-44dc-ab39-58341ba8af19.png)

So this time the difference between BERV has a bigger amplitude when using the same input ! 

As a final existence here is GL725B for which there is a ~5m/s BERV difference using the same input and a < 1 m/s BERV difference using different input 

![image](https://user-images.githubusercontent.com/76592606/135463411-59d08096-0317-41e4-8f6e-b6625e11b405.png)

![image](https://user-images.githubusercontent.com/76592606/135463457-0548c908-8ed2-422b-8c30-b9d9176412b7.png)

**Comment by njcuk9999** [comment]
Okay sorry you are going to have to be more specific

That piece of code you mention doesn't say anything about the values you are actually using.

Why even bother doing the LBL at all? Why not plot (on a single graph) the BERV using "your method" and the BERV from the 0.6 version? Adding the LBL in just complicates things for no reason.


I have never used the `get_stellar_data` function in barycorrpy - you have to also remember you may not be using the same barycorrpy as used in the 0.6 version (you'd have to check with Andres which version he is using).


What I would want to see for this problem is the following:
1. Your "stellar parameters" vs the 0.6 stellar parameters - you say they are "all different" but this doesn't help (for the same object)
2. A plot of the BERV vs MJD for "your BERV" vs the BERV in 0.6


Also I'm still not sure what you mean by "the same input" - the same input to what? Its not the "same input" if you are using your coordinates? So I'm confused about your definition of the "same" - could you explain?

**Comment by HkmMerwan** [comment]
> 
> 
> Okay sorry you are going to have to be more specific
> 
> That piece of code you mention doesn't say anything about the values you are actually using.
> 
> Why even bother doing the LBL at all? Why not plot (on a single graph) the BERV using "your method" and the BERV from the 0.6 version? Adding the LBL in just complicates things for no reason.

Because you can't see by eye a m/s difference when the amplitude is of km/s

I do not add the LBL in those plot. I compute the difference between the BERV I compute and the BERV I retrieve from APERO, I only mean that I get the BERV value from the lbl file in one of the columns.

> I have never used the `get_stellar_data` function in barycorrpy - you have to also remember you may not be using the same barycorrpy as used in the 0.6 version (you'd have to check with Andres which version he is using).
> 
> What I would want to see for this problem is the following:
> 
>     1. Your "stellar parameters" vs the 0.6 stellar parameters - you say they are "all different" but this doesn't help (for the same object)

RA DEC PMRA PMDEC PX RV 

```
GL725B: 

APERO HEADER: 280.6834710369766  59.63488676562468 -1400.02327982324  1862.40749525787 283.8624454179554 -9999.99

GET_STELLAR_DATA: 280.69539249999997 59.6268675 -1400.023 1862.407 283.8624 1190.0


GL411:  

APERO HEADER: 165.831125  35.94369444444444 -579.9999999999999  -4769.999999999999  0.0 -9999.99

GET_STELLAR_DATA: 165.83414499999998 35.969882222222225 -580.057 -4776.589 392.7529  -84640.0

```

get stellar data simply take the data from simbad

>     2. A plot of the BERV vs MJD for "your BERV" vs the BERV in 0.6

If you want but you won't see the difference by eye, here is this plot when I compute the BERV using the parameters from APERO (red) and in black the BERV value (GL725B) in km/s

![image](https://user-images.githubusercontent.com/76592606/135468937-8650eb97-0934-4c98-adf8-18ffe97345c5.png)


And their difference 

![image](https://user-images.githubusercontent.com/76592606/135468980-8c4dcf2d-6d03-4b93-9d80-0514542f485e.png)

> 
> Also I'm still not sure what you mean by "the same input" - the same input to what? Its not the "same input" if you are using your coordinates? So I'm confused about your definition of the "same" - could you explain?

The same input means computing barycorrpy with the stellar parameters from the header

Different input means computing barycorrpy with the stellar parameters from the get_stellar_data function (ergo simbad)

**Comment by njcuk9999** [comment]
Okay but APERO doesn't use these header keys: `RA DEC PMRA PMDEC PX RV`
It uses the BC_XXX keys

BC_GAIA =   909820931110880640 / The Gaia ID used for BERV params
BC_OBJNM= '33Lyn   '           / The OBJNAME used for BERV params
BC_RA   =    128.6827139477187 / Right Ascension used to calc. BERV
BC_DEC  =    36.41944482164627 / Declination used to calc. BERV
BC_EPOCH=    2457205.999994213 / Epoch [JD] used to calc. BERV
BC_PMRA =   -26.11661600568005 / PMRA [mas/yr] used to calc. BERV
BC_PMDE =   -40.89996873740448 / PMDE [mas/yr] used to calc. BERV
BC_LAT  =            19.825252 / OBS Latitude [deg] used to calc. BERV
BC_LONG =          -155.468876 / OBS Longitude [deg] used to calc. BERV
BC_ALT  =               4204.0 / OBS Altitude [m] used to calc. BERV
BC_PLX  =    9.995273103686801 / PLX [mas] used to calc. BERV
BC_RV   =                  0.0 / RV [km/s] used to calc. BERV
BC_PSRCE= 'GAIA [TABLE]'       / Source of BERV star params
BC_GMAG =    5.730706214904785 / Gaia G mag for BERV calc.
BC_BPMAG=    5.770686149597168 / Gaia BP mag for BERV calc.
BC_RPMAG=    5.689286231994629 / Gaia RP mag for BERV calc.
BC_MAG_L=                 15.0 / Gaia mag lim for BERV calc.
BC_PLX_L=                  5.0 / Gaia plx lim for BERV calc.




As for your problem about not seeing the difference at m/s as you've done just taking the difference works!
Sorry your graphs confused me because the y-axis says "RV"  not "BERV" 


The values from SIMBAD are from where exactly? I'm nervous of this approach as I'm not sure how consistent the BERV values are. 

The whole reason we use Gaia is to get the best possible parameters - these are NOT available in the spirou headers using `RA DEC PMRA PMDEC PX RV` - hence crossmatching with Gaia

So my next question is how does this change your results if you use the BC_XXX keys ?  Are the parameters more consistent with SIMBAD?

And also you'd have to see how the version of barycorrpy affects the "same input" - is it just a barycorrpy update that has changed this (0.7 uses a newer version)?

**Comment by HkmMerwan** [comment]
The RA DEC etc value I showed from APERO do come from the header BC_RA BC_DEC

**Comment by HkmMerwan** [comment]
The values from SIMBAD are from GAIA, quick check on their website shows that the value I have with the get_stellar_data function are the correct ones (at least the ones on the website)

**Comment by HkmMerwan** [comment]
So to be clear, all the plots I showed already use the BC_XXX keys

**Comment by HkmMerwan** [comment]
Moved the discussion to slack.
