### ISSUE TITLE
A Type Error happening due to different versions of python

### ISSUE THREAD

**Issue by JoanneJi** [njcuk9999/apero-drs#683]
I am installing APERO on Windows subsystem for Linux with python on 3.9.13. When I did '3.1 the installation script', an unexpected Type Error happened. I commented line 1437 '**time.sleep(rint)**' in "drs_startup.py" and the installation process succeeded.  I think this error is caused by different versions of python. Are there any other explanations? 
Thanks a lot! :)
![image](https://user-images.githubusercontent.com/88363897/201468549-25779c4d-bd5b-4f2e-a1ee-3560ad611547.png)

**Comment by njcuk9999** [comment]
Hi, which branch are you using?
Could you try with v0.7.254-stable-test?
The main and developer branches are out of date (v0.6) I think this may be fixed in the 0.7 branches.

If you still have this problem I can try to fix it. I've not tested windows or windows with wsl so there may be a few problems that need fixing!

**Comment by JoanneJi** [comment]
> 

Thanks a lot for your reply! I tried the newest branch and found it went on successfully on my new m1 Mac. That's so great! 👍
