### ISSUE TITLE
lbl.log   saved in home directory, not in msg/ ?  (0.7.288)

### ISSUE THREAD

**Issue by larnoldgithub** [njcuk9999/apero-drs#741]
At the end of the LBL processing (lbl_run.ini with apero_proecessing.py), APERO took a few minutes to generate a log file, lbl.log. It is saved in my home directory. Why not in msg/   ?

**Comment by njcuk9999** [comment]
This is because LBL is completely separate from APERO - it is like another module (like numpy or matplotlib).
Therefore LBL inside apero does what it does outside APERO.

Note that the logs from LBL are copied back into the apero_lbl recipe logs so they are all there... you just get the log from LBL as well (for people using LBL without apero).

Maybe there would be a way to turn this off, but it isn't a priority at the moment.
