### ISSUE TITLE
[APERO] Allow running `apero_reject.py` on multiple identifiers at once

### ISSUE THREAD

**Issue by vandalt** [njcuk9999/apero-drs#767]
For cases where many files are rejected using filenames, having the option to pass multiple identifiers at once would be useful.

My understanding by quickly looking at the code is this is not currently possible. The workaround to use a bash loop works, but is a bit less safe and requires confirming and uploading for each file.

**Comment by njcuk9999** [comment]
Okay I think these changes work now. I have done as follows:

- allowed comma separated list for the identifiers and objnames
- allowed a keyword `--obsdir`  which overrides `--identifier` and puts all files that are not science observations for a night into a list of identifiers (exactly the same as doing `--identifier=XXXX,YYYY,ZZZZ`
- added a table print out of the list of files that will be removed (with FILENAME, OBSDIR, DPRTYPE) and ask the user to check this is correct and reject rows if they don't want all files
- The comment is for all files (same as the PP/TELL/RV step) no longer have to do this per file

This should work for all instruments but probably needs testing.

I'll see if I can add a "date added" column because that would make it easier to debug problems afterwards

**Comment by njcuk9999** [comment]
Okay should have a DATE_ADDED column now too (turns out inside apero I was adding this column any way)
